import {nanoid} from 'nanoid';

const menusdata = [
  {
    id: nanoid(),
    name: 'Kung Pao Chicken',
    image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491336/menu/Kung-Pao-chicken_owdyqj.jpg',
    price: 9.9,
    category: 'Mains',
    ingredients: 'chicken breast, peanuts, chili peppers, soy sauce, baking soda, cornstarch, salt, oil',
    taste: 'Spicy, Salty, Sweet',
    spiciness: 3,
    reviews: [
      {
        id: nanoid(),
        image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491336/menu/Kung-Pao-chicken_owdyqj.jpg',
        guest: 'Guest A',
        text: 'This was the best Kung Pao chicken I have ever had.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest B',
        text: 'Very spicy, too much for me, but everyone else loved it.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest C',
        text: 'We also prefer cashews over the peanuts but either tastes good.',
      },
    ],
  },
  {
    id: nanoid(),
    name: 'Peking Duck',
    image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656683121/menu/Peking-Duck_s8bedg.jpg',
    price: 12.9,
    category: 'Mains',
    ingredients: 'duck, lemon, honey, soy sauce, flour, spring onions, hoisin sauce, salt, oil',
    spiciness: 0,
    reviews: [
      {
        id: nanoid(),
        image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656683121/menu/Peking-Duck_s8bedg.jpg',
        guest: 'Guest A',
        text: 'This was the best Peking Duck I have ever had.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest B',
        text: 'Very crispy, everyone loved it.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest C',
        text: "The food wasn't bad, but wasn't wow..",
      },
    ],
  },
  {
    id: nanoid(),
    name: 'Sweet and Sour Pork',
    image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491337/menu/Sweet-and-Sour_Pork_mku0nw.jpg',
    price: 10.9,
    category: 'Mains',
    ingredients:
      'Pork, bell pepper, pineapple, cornstarch, ketchup, brown sugar, vinegar, garlic, ginger, onion, salt, oil',
    taste: 'Sweet, Sour, Salty',
    spiciness: 0,
    reviews: [
      {
        id: nanoid(),
        image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491337/menu/Sweet-and-Sour_Pork_mku0nw.jpg',
        guest: 'Guest A',
        text: 'This was the best Sweet and Sour Pork I have ever had.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest B',
        text: 'Very delicious, everyone loved it.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest C',
        text: "The food wasn't bad, but wasn't wow..",
      },
    ],
  },
  {
    id: nanoid(),
    name: 'Mapo Tofu',
    image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491337/menu/Mapo-Tofu_w8q2yw.jpg',
    price: 6.9,
    category: 'Mains',
    ingredients: 'Tofu, Chili Bohnen Paste, minced beef, salt, oil',
    taste: 'Spicy, Salty',
    spiciness: 3,
    reviews: [
      {
        id: nanoid(),
        image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491337/menu/Mapo-Tofu_w8q2yw.jpg',
        guest: 'Guest A',
        text: 'This was the best Mapo Tofu I have ever had.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest B',
        text: 'Very delicious, everyone loved it.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest C',
        text: "The food wasn't bad, but wasn't wow..",
      },
    ],
  },
  {
    id: nanoid(),
    name: 'Twice Cooked Pork',
    image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491338/menu/Twice-Cooked-Pork_hvovno.jpg',
    price: 12.9,
    category: 'Mains',
    ingredients:
      'pork belly, bell pepper, chili bean paste,sweet bean paste , ginger, leek, Sichuan peppercorn, soy sauce, salt, oil',
    taste: 'Spicy, Salty',
    spiciness: 2,
    reviews: [
      {
        id: nanoid(),
        image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491338/menu/Twice-Cooked-Pork_hvovno.jpg',
        guest: 'Guest A',
        text: 'This was the best Twice Cooked Pork I have ever had.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest B',
        text: 'Very delicious, everyone loved it.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest C',
        text: "The food wasn't bad, but wasn't wow..",
      },
    ],
  },
  {
    id: nanoid(),
    name: 'Yuxiang Eggplant',
    image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491338/menu/Yu-Xiang-Eggplant_oyo3ai.jpg',
    price: 12.9,
    category: 'Mains',
    ingredients:
      'eggplant, fresh shiitake, garlic, ginger, green onionsoy sauce, oyster sauce, vinegar, brown sugar, cornstarch, sesame oil, salt, oil',
    taste: 'Spicy, Sweet, Sour, Salty',
    spiciness: 1,
    reviews: [
      {
        id: nanoid(),
        image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491338/menu/Yu-Xiang-Eggplant_oyo3ai.jpg',
        guest: 'Guest A',
        text: 'This was the best Yuxiang Eggplant I have ever had.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest B',
        text: 'Very delicious, everyone loved it.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest C',
        text: "The food wasn't bad, but wasn't wow..",
      },
    ],
  },
  {
    id: nanoid(),
    name: 'Squirrel Shaped Mandarin Fish',
    image:
      'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491337/menu/squirrel-shaped-mandarin-fish_y74urn.jpg',
    price: 19.9,
    category: 'Mains',
    ingredients: 'grass carp, Starch, minced garlic, Ketchup, sugar, soy sauce, vinegar, broth, salt, oil',
    taste: 'Sweet, Sour, Salty',
    spiciness: 0,
    reviews: [
      {
        id: nanoid(),
        image:
          'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491337/menu/squirrel-shaped-mandarin-fish_y74urn.jpg',
        guest: 'Guest A',
        text: 'This was the best Squirrel Shaped Mandarin Fish I have ever had.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest B',
        text: 'Very delicious, everyone loved it.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest C',
        text: "The food wasn't bad, but wasn't wow..",
      },
    ],
  },
  {
    id: nanoid(),
    name: 'Fried Mushroom',
    image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491336/menu/Fried_Mushroom_br3rhv.jpg',
    price: 7.9,
    category: 'Mains',
    ingredients: 'Oyster Mushroom, salt and black pepper to taste, flour, egg, salt, oil',
    taste: 'Salty',
    spiciness: 0,
    reviews: [
      {
        id: nanoid(),
        image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491336/menu/Fried_Mushroom_br3rhv.jpg',
        guest: 'Guest A',
        text: 'This was the best Fried Mushroom I have ever had.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest B',
        text: 'Very crispy, everyone loved it.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest C',
        text: "The food wasn't bad, but wasn't wow..",
      },
    ],
  },
  {
    id: nanoid(),
    name: 'Celery and dried bean cord',
    image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491337/menu/Celery_and_dried_bean_cord_yapjzf.jpg',
    price: 12.9,
    category: 'Starters',
    ingredients: 'celery stems, dry bean curd, onion, ginger, white vinegar, salt, oil',
    taste: 'Spicy, Sweet, Salty',
    spiciness: 1,
    reviews: [
      {
        id: nanoid(),
        image:
          'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491337/menu/Celery_and_dried_bean_cord_yapjzf.jpg',
        guest: 'Guest A',
        text: 'This was the best Celery and dried bean cord I have ever had.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest B',
        text: 'Very delicious, everyone loved it.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest C',
        text: "The food wasn't bad, but wasn't wow..",
      },
    ],
  },
  {
    id: nanoid(),
    name: 'Tossed Cucumber in Sauce',
    image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491338/menu/Tossed_Cucumber_in_Sauce_nvt4zt.jpg',
    price: 4.9,
    category: 'Starters',
    ingredients: 'cucumbers, granulated sugar, rice vinegar, sesame oil, light soy sauce, salt, oil',
    taste: 'Spicy, Sweet, Sour, Salty',
    spiciness: 2,
    reviews: [
      {
        id: nanoid(),
        image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656491338/menu/Tossed_Cucumber_in_Sauce_nvt4zt.jpg',
        guest: 'Guest A',
        text: 'This was the best Tossed Cucumber in Sauce I have ever had.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest B',
        text: 'Very delicious, everyone loved it.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest C',
        text: "The food wasn't bad, but wasn't wow..",
      },
    ],
  },
  {
    id: nanoid(),
    name: 'Water',
    image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656490204/menu/Water_h8f4lh.jpg',
    price: 1.9,
    category: 'Drinks',
  },
  {
    id: nanoid(),
    name: 'Apple Spritzer',
    image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656490203/menu/Apfelschorle_zxhwrj.jpg',
    price: 1.9,
    category: 'Drinks',
  },
  {
    id: nanoid(),
    name: 'Beer',
    image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656490203/menu/beer_ppyotj.jpg',
    price: 2.9,
    category: 'Drinks',
  },
  {
    id: nanoid(),
    name: 'Chrysanthemum Tea',
    image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656490202/menu/Chrysanthemum_Tea_mjx9vn.jpg',
    price: 2.9,
    category: 'Drinks',
  },
  {
    id: nanoid(),
    name: 'Fried Glutinous Rice Balls With Sesame',
    image:
      'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656490182/menu/Fried_Glutinous_Rice_Balls_with_Sesame_l8smoa.jpg',
    price: 4.9,
    category: 'Pastries',
    ingredients: 'red bean, sugar, glutinous rice flour, sesame, salt, oil',
    taste: 'Sweet',
    spiciness: 0,
    reviews: [
      {
        id: nanoid(),
        image:
          'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656490182/menu/Fried_Glutinous_Rice_Balls_with_Sesame_l8smoa.jpg',
        guest: 'Guest A',
        text: 'This was the best Fried Glutinous Rice Balls I have ever had.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest B',
        text: 'Very delicious, everyone loved it.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest C',
        text: "The food wasn't bad, but wasn't wow..",
      },
    ],
  },
  {
    id: nanoid(),
    name: 'Yolk Pastry',
    image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656490179/menu/Yolk_Pastry_d3bmmm.jpg',
    price: 2.9,
    category: 'Pastries',
    ingredients: 'flour, red beans, butter, white sugar, butter, sugar, egg yolk, lemon, sesame, salt, oil',
    taste: 'Sweet',
    spiciness: 0,
    reviews: [
      {
        id: nanoid(),
        image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656490179/menu/Yolk_Pastry_d3bmmm.jpg',
        guest: 'Guest A',
        text: 'This was the best Yolk Pastry I have ever had.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest B',
        text: 'Very delicious, everyone loved it.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest C',
        text: "The food wasn't bad, but wasn't wow..",
      },
    ],
  },
  {
    id: nanoid(),
    name: 'Mochi Balls',
    image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656490180/menu/Mochi_Balls_jfydgr.jpg',
    price: 2.9,
    category: 'Pastries',
    ingredients: 'glutinous rice flour, red Bean, green tea powder, sugar, cornstarch, salt, oil',
    taste: 'Sweet',
    spiciness: 0,
    reviews: [
      {
        id: nanoid(),
        image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656490180/menu/Mochi_Balls_jfydgr.jpg',
        guest: 'Guest A',
        text: 'This was the best Mochi Balls I have ever had.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest B',
        text: 'Very delicious, everyone loved it.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest C',
        text: "The food wasn't bad, but wasn't wow..",
      },
    ],
  },
  {
    id: nanoid(),
    name: 'Dim Sum',
    image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656490181/menu/Sim_Sum_sw2nbo.jpg',
    price: 2.9,
    category: 'Pastries',
    ingredients:
      'chicken breast, flour, napa cabbage, shiitake mushrooms, wheat starch, sugar, yeast, baking powder, salt, oil',
    taste: 'Sweet, Salty',
    spiciness: 0,
    reviews: [
      {
        id: nanoid(),
        image: 'https://res.cloudinary.com/ddbcljw3g/image/upload/v1656490181/menu/Sim_Sum_sw2nbo.jpg',
        guest: 'Guest A',
        text: 'This was the best Dim Sum I have ever had.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest B',
        text: 'Very delicious, everyone loved it.',
      },
      {
        id: nanoid(),
        image: '',
        guest: 'Guest C',
        text: "The food wasn't bad, but wasn't wow..",
      },
    ],
  },
];

export default menusdata;
